// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtxuh4SoFdO9pzP9tLUsx0OIuiOM0hwuM',
    appId: '1:187650946445:web:dc1d1e61fd59c06b2df9c4',
    messagingSenderId: '187650946445',
    projectId: 'last-mile-delivery-7951f',
    authDomain: 'last-mile-delivery-7951f.firebaseapp.com',
    storageBucket: 'last-mile-delivery-7951f.firebasestorage.app',
    measurementId: 'G-S3RMNFGC8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk06B-SXBYnIKcfP57xuEY-Oy2Bt8iTyw',
    appId: '1:187650946445:android:7c1a62f495bcb7e82df9c4',
    messagingSenderId: '187650946445',
    projectId: 'last-mile-delivery-7951f',
    storageBucket: 'last-mile-delivery-7951f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbFN4TUBO8MxCXKnlBPA5LbxWjcViZeIA',
    appId: '1:187650946445:ios:5b8aaf41076e94ac2df9c4',
    messagingSenderId: '187650946445',
    projectId: 'last-mile-delivery-7951f',
    storageBucket: 'last-mile-delivery-7951f.firebasestorage.app',
    iosBundleId: 'com.example.lastMileDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbFN4TUBO8MxCXKnlBPA5LbxWjcViZeIA',
    appId: '1:187650946445:ios:5b8aaf41076e94ac2df9c4',
    messagingSenderId: '187650946445',
    projectId: 'last-mile-delivery-7951f',
    storageBucket: 'last-mile-delivery-7951f.firebasestorage.app',
    iosBundleId: 'com.example.lastMileDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtxuh4SoFdO9pzP9tLUsx0OIuiOM0hwuM',
    appId: '1:187650946445:web:1cd047be7eb293c82df9c4',
    messagingSenderId: '187650946445',
    projectId: 'last-mile-delivery-7951f',
    authDomain: 'last-mile-delivery-7951f.firebaseapp.com',
    storageBucket: 'last-mile-delivery-7951f.firebasestorage.app',
    measurementId: 'G-BSQHRPPF2W',
  );
}
